// projects/focusf/src/lib/project/Projects.svelte
<script lang="ts">
	import { type ProjectUdto } from "$lib/project/models";
  import { onDestroy } from "svelte";
  import { selectedProjectSid } from "./stores";
  import { MongoUtils } from "$lib/mongo/utils";

  const unsubs: (() => void)[] = [];
  const Collection: string = "projectDoc";
  let projects: ProjectUdto[] = [];
  let nameInp: string = "";

  MongoUtils.getMany<ProjectUdto>(Collection, {}, unsubs, val =>
    projects = [...projects, ...val]
  );

  onDestroy(() => unsubs.map(fn => fn()));
</script>

<div
  class="
    flex flex-col gap-4 justify-center items-center text-c30-fg
    bg-c30-bg p-4 rounded
  "
>
  {#if projects.length > 0}
    {#each projects as project}
      <div class="flex flex-row justify-center items-center gap-4">
        <button on:click={() => selectedProjectSid.set(project.sid)}>
          <span
            class={
              $selectedProjectSid === project.sid
              ? "underline"
              : "hover:underline"
            }
          >
            {project.name}
          </span>
        </button>
        <button
          class="bg-red-500 rounded p-2 hover:bg-red-300 text-sm"
          on:click={() => MongoUtils.delBySid(
            Collection, project.sid, unsubs, () =>
            {
              projects.splice(
                projects.findIndex(v => v.sid == project.sid),
                1
              );
              projects = projects;
            }
          )}
        >
          <span>X</span>
        </button>
      </div>
    {/each}
  {/if}

  <div class="flex flex-row items-center justify-center gap-2">
    <input class="text-black" bind:value={nameInp}/>
    <button
      class="bg-green-500 rounded p-2 hover:bg-green-300 text-xl"
      on:click={(() => nameInp.trim() !== ""
        ? MongoUtils.create(
          Collection,
          { name: nameInp },
          unsubs,
          val => projects = [...projects, val]
        )
        : undefined
      )}
    >
      new
    </button>
  </div>
</div>

// projects/client/src/app/project/projects/projects.component.ts
import { Component, OnInit } from "@angular/core";
import { ProjectUdto } from "src/app/models";
import { ProjectService } from "../project.service";
import { FormControl, FormGroup } from "@angular/forms";
import { InputType } from "@almazrpe/ngx-kit";

@Component({
  selector: "app-projects",
  templateUrl: "./projects.component.html",
  styles: [
  ]
})
export class ProjectsComponent implements OnInit
{
  public InputType = InputType;

  public projects: ProjectUdto[] = [];
  public projectCreateForm: FormGroup;
  private unsubs: (() => void)[];

  public constructor(
    private projectSv: ProjectService)
  {}

  public ngOnInit(): void
  {
    this.projectSv.getMany$().subscribe({next: val => this.projects = val});
    this.projectCreateForm = new FormGroup({
      name: new FormControl("")
    });
  }

  public ngOnDestroy(): void
  {
    for (const unsub of this.unsubs)
    {
      unsub();
    }
  }

  public onKeydownEnter(): void
  {
    this.onProjectCreateSubmit();
  }

  private getDistilledProjectNameInput(): string
  {
    return this.projectCreateForm.value.name.trim();
  }

  public onProjectCreateSubmit(): void
  {
    const name = this.getDistilledProjectNameInput();
    if (name === "")
    {
      return;
    }
    this.projectSv.create$({name: name}).subscribe({
      next: val => this.projects.splice(0, 0, val)});
    this.projectCreateForm.setValue({name: ""});
  }

  public selectProject(project: ProjectUdto): void
  {
    this.projectSv.currentProject$.next(project);
  }

  public getProjectSelectors(project: ProjectUdto): string[]
  {
    if (this.projectSv.currentProject$.value?.sid === project.sid)
    {
      return ["underline"];
    }
    return [];
  }

  public delProject(project: ProjectUdto): void
  {
    this.projectSv.del$(project.sid).subscribe({
      next: _ =>
      {
        const deldProject = this.projects.indexOf(project);
        if (this.projectSv.currentProject$.value?.sid === project.sid)
        {
          this.projectSv.currentProject$.next(null);
        }
        this.projects.splice(deldProject, 1);
      }});
  }
}

<div class="
    flex bg-c30-bg h-screen p-4 flex flex-col justify-start items-center">
  <div class="font-bold mb-4">Projects</div>

  <form
      class="flex flex-row gap-4 justify-center items-center"
      [formGroup]="projectCreateForm"
      (ngSubmit)="onProjectCreateSubmit()">
    <ngx-kit-mat-input
        class="text-black"
        [type]="InputType.Text"
        (keydown.enter)="onKeydownEnter()"
        formControlName="name" />
    <ngx-kit-button
        type="submit"
        [extraCssClasses]="[
          'bg-c10-bg', 'text-c10-fg', 'hover:bg-c10-bg-active',
          'hover:text-c10-fg-active', 'rounded', 'h-8'
        ]">
      +
    </ngx-kit-button>
  </form>

  <div
      class="mt-8 flex flex-row justify-center items-center gap-4"
      *ngFor="let project of projects">
    <ngx-kit-button
        class="text-2xl hover:underline"
        [ngClass]="getProjectSelectors(project)"
        (clickFunc)="selectProject(project)">
      {{project.name}}
    </ngx-kit-button>
    <ngx-kit-button
        [extraCssClasses]="['bg-red-500', 'hover:bg-red-400', 'h-8']"
        (clickFunc)="delProject(project)">
      X
    </ngx-kit-button>
  </div>
</div>
